spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
        - id: items-service
          uri: lb://item-service
          predicates:
            - Path=/api/items/**  
          filters:
            - StripPrefix=2